### PR TITLE
Increment version number

### PR DESCRIPTION
**Pull request by jamiesnape**
Version number was not incremented before previous (2.1) release, so it is difficult to distinguish between 2.0 and 2.1. Making a 2.2 release with the correct version set would therefore be very helpful.

PTAL @danfis.

### CODE REVIEW

**Comment by traversaro** [comment]
I guess this problem is also affecting the libccd 2.1 currently shipping in Debian sid and that are  going to be used in Ubuntu Focal cc @j-rivero

**Comment by j-rivero** [comment]
> I guess this problem is also affecting the libccd 2.1 currently shipping in Debian sid and that are going to be used in Ubuntu Focal cc @j-rivero

Right. If we merge this PR and create a new release I can try to push it to Debian as soon as possible so we get some testing and sync for Ubuntu Focal before it finished as the end of the month.

**Comment by traversaro** [comment]
> > I guess this problem is also affecting the libccd 2.1 currently shipping in Debian sid and that are going to be used in Ubuntu Focal cc @j-rivero
> 
> Right. If we merge this PR and create a new release I can try to push it to Debian as soon as possible so we get some testing and sync for Ubuntu Focal before it finished as the end of the month.

That would be great, even if I  am afraid that @danfis has not been active lately on GitHub.

**Comment by jamiesnape** [comment]
It has been about two years since this opened, so this probably is not going to merge.

**Pull request closed without merging**
