### PR TITLE
Bring cmake build up to parity with autotools and add documentation

### PR DESCRIPTION
**Pull request by jamiesnape**
This refactors and enhances the cmake build to add missing targets for documentation and the test suite. It also adds the missing documentation for the cmake build, adds the necessary macros for exporting functions for building shared libraries on Windows using cmake, and adds exported targets and config files for ease of use of libccd in other cmake builds.

### CODE REVIEW

**Comment by jamiesnape** [comment]
I added a CMake build to `.travis.yml` so there is CI coverage of this PR.

**Comment by jslee02** [comment]
I have a suggestion on configuring CMake config file and version file for libccd. [CMake provides a helper function](https://cmake.org/cmake/help/v2.8.11/cmake.html#module:CMakePackageConfigHelpers) that can automatically generate those files. Using the function would be less buggy rather than maintaining the manual files manually.

**Comment by jamiesnape** [comment]
Sure, if you prefer. I always deliberately avoid that function, but I can make the change.

**Comment by jslee02** [comment]
Oh, I thought it's a recommended way by CMake. If this is a matter of preference then I think it should be determined by @danfis but not me. Thanks for the consideration though.

**Comment by mamoll** [comment]
👍 I'm not a libccd developer, but do use it in other cmake-based projects.

**Comment by danfis** [comment]
Merged, thanks guys.

**Pull request merged**
